### ISSUE TITLE
Tab panel component still in light color

### ISSUE THREAD

**Issue by michioxd** [BlueMystical/Dark-Mode-Forms#1]
Hello, thanks for your pretty nice work, but tab panel border and tab button still in light mode, you can see this picture below

![image](https://github.com/BlueMystical/Dark-Mode-Forms/assets/80969068/6e93a2e4-6740-4161-86bc-e1b6a30aa5c4)

**Comment by BlueMystical** [comment]
hi there!, thank you for making me notice it.
Yes i just uploaded this yesterday, still a Work In Progress, ill be uploading a new version in a few hours with several changes and improvements, Tabcontrol Included.

**Comment by BlueMystical** [comment]
Well..  TabControl is now Dark
![image](https://github.com/BlueMystical/Dark-Mode-Forms/assets/10116951/e1de8b3d-f280-469c-ac15-f1a889989b0f)

However i still had not figured out how to get rid of that border on the selected Header but im not done yet.

Regards.

**Comment by michioxd** [comment]
Nice work, thanks so much!
