### ISSUE TITLE
Repository Re-construction

### ISSUE THREAD

**Issue by TetraTheta** [BlueMystical/Dark-Mode-Forms#10]
This is just a suggestion. If you don't want to do this, you can just close this issue as 'not planned'.

I think this repository has few minor structural problems.

* Duplicated files like [`DarkModeCS.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/main/DarkModeCS.cs) and [`DarkModeCS.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/main/Example/DarkModeForms/DarkModeCS.cs)
* Lack of 'coding style guideline' like `.editorconfig`  
  VS supports additional `.editorconfig` entries
* Included files that aren't needed to repository  
  Why do we have [`DarkModeForms_v1.3.1.zip`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/main/Example/DarkModeForms/DarkModeForms_v1.3.1.zip) in this repository?

This makes me hard to contribute to this repository. Editing files in VS will reformat everything to my coding style, so I have to modify them via notepad which prevents me from using 'code completion', 'error detection' etc. that VS provides.

So I suggest re-constructing this respository to make this repository to be easy to maintain and easy to contribute.

---

## Move 'Example' to the top

First, we have to move 'Example' project to root directory.

```plaintext
<root>
├ .git
├ Properties
├ Resources
│ 
│ DarkModeForms.sln
│ README.md
└ (and other files)
```

## Create centralized 'DarkModeForms' library directory

Then, create 'DarkModeForms' directory that contains every library files that this repository provides:
* [`DarkModeCS.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/main/Example/DarkModeForms/DarkModeCS.cs)
* [`FlatComboBox.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/main/Example/DarkModeForms/FlatComboBox.cs)
* [`FlatTabControl.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/main/Example/DarkModeForms/FlatTabControl.cs)
* [`Messenger.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/main/Example/DarkModeForms/Messenger.cs)

```plaintext
<root>
├ .git
├ DarkModeForms
│ │ DarkModeCS.cs
│ │ FlatComboBox.cs
│ │ FlatTabControl.cs
│ └ Messenger.cs
├ Properties
├ Resources
│ 
│ DarkModeForms.sln
│ README.md
└ (and other files)
```

Every modifications for this library files must be done in these files under 'DarkModeForms' directory only. Duplicated files must not be created.

With this, we can 'focus' contribution and distribution on these files.

## Create `.editorconfig` and `.gitignore`

After that, we now create `.editorconfig` and `.gitignore` files.

VS supports `.editorconfig` configuration by default. You can create your own `.editorconfig` file at the root of this repository, or refer to my own [`.editorconfig`](https://github.com/TetraTheta/Small-Projects/blob/main/Pathed/.editorconfig) as an example.  
My `.editorconfig` file is nested and minified, so it lacks of 'root' configuration and comments. I can provide 'merged' version of my `.editorconfig`s, if you want.

You have to include the newly created `.editorconfig` file to the project, if you didn't create it within VS.

`.gitignore` makes Git to ignore files, so that they won't be uploaded or tracked. I suggest you to use [`.gitignore` generated with Toptal](https://www.toptal.com/developers/gitignore/api/rider,csharp,intellij+all,visualstudio,visualstudiocode,archive,archives), but you can make your own `.gitignore` with [this](https://www.toptal.com/developers/gitignore?templates=rider,csharp,intellij+all,visualstudio,visualstudiocode,archive,archives).

## Reformat every files in VS

Since we have `.editorconfig` file that controls coding style, you should reformat every files in your project via VS. If your VS recognizes `.editorconfig`, style of those codes should be changed consistently.

## Remove excessive files from Git index

Since we now have `.gitignore`, we can safely remove files that should not be tracked from Git index.
```bash
# This commands are for Bash
# Move to repository root
# If you use Windows, use 'cd /d "C:\path\to\repo\root"' instead
cd "/path/to/repo/root"
# Untrack everything from Git index temporarily
# git command will work on any OS if installed correctly
git rm --cached -r .
# Re-add important files to Git index
git add .
```
These commands won't remove physical files, so don't worry. No files will be edited or be removed. These commands will only modify Git index.

## Check before commit/push

If you have Git GUI, you can easily check how files will be modified or be removed/created within GUI. That will help you from fixing problems before pushing your commit to GitHub.

## Push!

If you think everything is OK, you can push your commits to GitHub.

## Publishing

When you want to publish new version, just zip 'DarkModeForms' that has library files and upload it. Since it is the only source of your library, everything would be up-to-date.

---

I tried to do it myself and create a PR, but I'm afraid that it will enforce you (and everyone) to use my coding style, and you might be uncomfortable with my coding style.  
Best way of adapting this is, you configure your own coding style and apply it.

If you have any question about this re-construction, feel free to ask me about it. I'll help as much as I can.

**Comment by BlueMystical** [comment]
hi, thank you for your suggestions, they seems really useful.
Im just not too used to the ways of Github, specially the console commands, i just upload the files using the web interface.. yeahh... lame i know.
i'll try to implement some of your suggestions.

Thanks again.

**Comment by TetraTheta** [comment]
If you need any help about implementing this suggestion, feel free to ask me. I'll help you as much as I can.

Since VS tends to be pesky about `.editorconfig` recognition, you might have to manually edit `.sln` or `.csproj` files to include `.editorconfig` file to your project.

If you use Linux or MacOS, `git` command should be already included in your OS. For Windows, 'Git for Windows' that also provides minified MSYS2 environment exists. You can read about Git stuff from [here](https://git-scm.com/book/en/v2), and [how to install Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git).

I wish you the best of luck!

**Comment by kachnitata** [comment]
Hello TetraTheta, 
thank you for your guidelines. I discovered this project just a few days ago, and I am working my own improvements (a tiny portion of which I have already sent to BlueMystic and he included them in the last release). I would be happy to contribute.

I would also be grateful if you continue sharing any future comments publicly here.
I have been developing software using other platforms for more than 25 years but I am very new to Github and want to learn to use it properly.

regards
Jakub

**Comment by TetraTheta** [comment]
@jurakovic Instead of sending modified files to BlueMystical, you really should create PR for it.

1. Fork this repository
2. Create separate branch from `main`  
  You'll be messed up if you use `main` when you want to do another contribution. That's why you use separated branch from `main`.
3. Commit changes to the separate branch
4. (Optional) Rebase and merge your commits into one commit  
  BlueMystical can also merge those commits into one when accepting PR. But that is not that easy to understand, at least for me.
5. Create a Pull Request from the separate branch  
  You can add more commits to the branch until PR is closed (accepted/denied)
6. BlueMystical decides
7. DONE

Since the only proof of your contribution is brief mention from BlueMystical, in GitHub's perspective, you are not contributor.

If you understand how Git and GitHub works, contributing become quite funny things to do. At least, it is for me.

---

I... have few more _suggestions_ about using Git and GitHub, but I'm afraid it would look like I'm enforcing/pushing you to use GitHub as I do, so I want to walk on eggshells around this.

<details>
<summary>'I might look like this', in meme picture</summary>
<br>

![a](https://github.com/BlueMystical/Dark-Mode-Forms/assets/37061801/9798d564-686d-49f2-8aa3-03a19b9878b0)

> No offense, please forgive me if you felt offended, or became uncomfortable from this.

</details>

**Comment by BlueMystical** [comment]
Hi guys, all and any contributions are gladly welcome, 
Feel free to send or Commit your changes and if they work and are better i'll just merge them.
Thanks!

**Comment by jurakovic** [comment]
> @jurakovic Instead of sending modified files to BlueMystical, you really should create PR for it.
> (...)

Man what are you talking about, who sent what modified files?

**Comment by TetraTheta** [comment]
> Man what are you talking about, who sent what modified files?

I don't know what exactly happened between kachnitata and BlueMystical. I'm just guessing that e4f06eb507bc17f0433aec3ad010c6d25dc755dc and 71df50a9be04ddb8353888777290dacf78bd4c63 are done from file sent by kachnitata and BlueMystical uploaded the modified file to GitHub.

My guess is from this comment by kachnitata and changelog of v1.6.2.

> ...
> a tiny portion of which I have already sent to BlueMystic and he included them in the last release
> ...
> 
> regards
> Jakub

> [Fixed a bug on the Toolstrip icon rendering, thanks to Jakub Jiříček](https://github.com/BlueMystical/Dark-Mode-Forms/releases/tag/v1.6.2)

If I misunderstood things, I'm really sorry about the misunderstanding.

You'd better ask kachnitata or BlueMystical directly for better understanding, if you still wonder.

**Comment by jurakovic** [comment]
Ok, I see now the whole thread. Do you see what is my username and who you were responding to? You tagged me in that comment with some "accusations" out of nowhere and I didn't know what was going on.

* * *

On topic, yes, I agree that there could be made some "structural changes" in repo. But BlueMystical is it's owner and he decides what and how he wants to do. It's fine to me if it's fine to him. I've forked it and I use it in one of my projects without issues and I'm very grateful for that.

**Comment by TetraTheta** [comment]
Oh, now I see why you were responding like that. I was mentioning wrong person... I'm awfully sorry. I edited original mention to point right person. I'm really sorry again.

---

Back to the topic, I'm currently waiting for the owner to apply those changes. If I understood right, he agreed with the repo reconstruction, so it will be done someday. I can wait for it.

**Comment by BlueMystical** [comment]
Soon ;-p

**Comment by TetraTheta** [comment]
You don't need to rush.

I know this would be hard to understand for who don't understand Git well. I've nuked whole (and months of) commit history when I first used Git and GitHub. :)

Also, since people who uses this library can just reformat files as they like in their repo. This is just minor, aesthetic issue (not a problem).

You can take your time. Also, sorry for the mess. :p

**Comment by kachnitata** [comment]
Hi guys, I have been offline for a while.
regarding the confusion: I think @TetraTheta just mistakenly tagged @jurakovic  instead of me.

I have made my own fork and I would love to add my edits but currently I am struggling with .editorconfig missing here, so my edits would break the indentation, at least (as @TetraTheta  said).
also, I find quite confusing that the main code depends on FlatComboBox, FlatTabControl which are stored in Example folder.

I would love if you @BlueMystical could put at least .editorconfig of your choice.

one more question, perhaps for @TetraTheta  -  what is the most convenient way of contributing? at first, when I came across Dark Mode Forms, , I just downloaded the individual files from here into my target project and adjusted them locally. Then I read your suggestions,and created a fork here on Github. How to integrate this fork with my local Visual Studio? do I need to install any add-ons (like Copilot)?

Regards

**Comment by TetraTheta** [comment]
> I think TetraTheta just mistakenly tagged jurakovic instead of me.

Yes, you're right. That's the reason of whole misunderstandings...

> .editorconfig missing here

That's why I suggested adding 'shared coding style' via `.editorconfig`. Visual Studio provides VS-only entries for coding style, so if we have `.editorconfig`, we won't struggle for manually _fixing_ [indentation style](https://en.wikipedia.org/wiki/Indentation_style#Notable_styles) or line breaks.

I use [CodeMaid](https://marketplace.visualstudio.com/items?itemName=SteveCadwallader.CodeMaidVS2022) for code formatting -- sometimes, VS code formatting doesn't work at all --, but I do believe that its configuration can also be shared.

> the main code depends on FlatComboBox, FlatTabControl which are stored in Example folder.

That's why I suggested to store every library files into `DarkModeForms` directory like this:
```plaintext
<root>
├ .git
├ DarkModeForms
│ │ DarkModeCS.cs
│ │ FlatComboBox.cs
│ │ FlatTabControl.cs
│ └ Messenger.cs
├ Properties
├ Resources
│ 
│ DarkModeForms.sln
│ README.md
└ (and other files)
```

'You only need `DarkModeCS.cs`' thing in README is sufficient. If anyone wants to use _smallest_ subset of this library, they will read that and use `DarkModeCS.cs` only.

> what is the most convenient way of contributing?
> How to integrate this fork with my local Visual Studio

VS itself is very good IDE. I only use [CodeMaid](https://marketplace.visualstudio.com/items?itemName=SteveCadwallader.CodeMaidVS2022) because VS's code formatting function sometimes completely stops working. Other things would be just personal preference, like IDE theme etc.

I'd recommend you to wait until reconstruction is complete first. Things are quite complicated with this structure.

<details>
<summary>But if you still want to participate to this repo now...</summary>

**Before start, I must say that after the reconstruction, things would be much simpler than this. These things will only work until reconstruction.**

This repository is already Git repository. So, forking this repository would be first thing to do, and you've already did it. Good job.

Now, you should clone the forked repo to your machine. VS provides a way to clone it, but I prefer using `git` command-line like `git clone <url to your fork repo>`. That's your choice, and how you clone your repo won't matter.

Open the cloned repository and create separate branch from `main`.
```bash
# Create 'my-modification' branch from 'main' branch
git branch my-modification main
# Checkout to 'my-modification' branch just created
git checkout my-modification
# You can use 'git checkout -b my-modification main' to combine these two commands into one
```
Now, you're on 'my-modification' branch of your fork.

Then, you download ZIP of your repo too. This is for not ruining _original_ code style by accident. All of your modifications will be done in ZIP extracted directory.

> NOTE: From here, I only assumed how files in this repo are managed, so there should be a chance that I misunderstand things. This is why I said 'wait until repo reconstruction completes'.

Open `.sln` file under `Example` of ZIP extracted directory. I guess every modifications are done in there first, then files are copied to root directory of the repo.

You do your modifications.

Open modified files on ZIP extracted directory and the same file on cloned repository side-by-side with Notepad++ (or any text editor you like) one by one.

While not ruining original coding style, precisly copy your modifications (and your modifications only) to files of cloned repository. Do not change Tab to Space or vice versa.

After copying is finished, run `git status` at cloned repository. You'll see few modified files. If the list only consist of modified files by you, run these commands:
```bash
# Stage all modified files
git add .
# Create commit with message
git commit -m "My Commit Message"
# Push your changes to your forked repository
git push origin my-modification
```

You should see 'my-modification' is newly created blahblah.

Now in GitHub, you can select the newly created 'my-modification' branch by clicking 'main'. Change to 'my-modification' branch.

After that, GitHub will nag you about your branch is X commit(s) ahead of BlueMystical/Dark-Mode-Forms and shows green button saying 'Create PR'. Click it to create PR.

If BlueMystical thinks it is good, he will merge it.

---

I created some images describing these procedures.

![1](https://github.com/BlueMystical/Dark-Mode-Forms/assets/37061801/b33c9b6c-34fb-44ac-ad0d-b5d8cc9e824f)

![2](https://github.com/BlueMystical/Dark-Mode-Forms/assets/37061801/5eadb7a7-1a64-45f7-b3d3-577aa2ea4311)

![3](https://github.com/BlueMystical/Dark-Mode-Forms/assets/37061801/767c9462-f7c7-47f2-baf1-92560a441fb0)

![4](https://github.com/BlueMystical/Dark-Mode-Forms/assets/37061801/eabf670f-2096-446e-aa16-bec2fed753bd)

![5](https://github.com/BlueMystical/Dark-Mode-Forms/assets/37061801/b2dcc06c-78f9-4e29-9f77-e89151f81b45)

![6](https://github.com/BlueMystical/Dark-Mode-Forms/assets/37061801/fa067aec-a6e4-4ab4-bbd8-f11a9c4276c1)

I'm bad at explanation, so pardon me about this poor explanations.

</details>

> do I need to install any add-ons (like Copilot)?

I guess you are saying 'GitHub Copilot'.

I strongly advise you not to use it. There are plenty of reasons not to use it. AI tends to generate looking-good-code like 'code with bad flow', 'non-existent methods' that aren't always legitimate. AI don't know what is 'right' or 'exists'. It just shows you series of words that looks good, not legitimate.

Use it only if you know how things should _flow_.

**Comment by kachnitata** [comment]
> I only use [CodeMaid](https://marketplace.visualstudio.com/items?itemName=SteveCadwallader.CodeMaidVS2022) because VS's code formatting function sometimes completely stops working
I have been using VS with Resharper happily for almost 10 years, so I will stick with it, but good to know there are other ways.

>But if you still want to participate to this repo now...
>I'm bad at explanation, so pardon me about this poor explanations.
on the contrary - amazing explanation. Even if I decide to wait for the reconstruction, it is great to learn this. 

>AI tends to generate looking-good-code [...] that aren't always legitimate
Agreed. I prefer simpler and transparent solutions too. (but, for eample the automatic refactorings in Resharper are a great time saver for me, but I think they are a different story as they are very predictable).

**Comment by BlueMystical** [comment]
Alright!
The Repo had been re-constructucted  v1.7.0
Many thanks guys for all your Suggestions, greatly appreciated.
Regards.

**Comment by BlueMystical** [comment]
@TetraTheta :  i had made and uploaded a `.editorconfig` file made default with VS.
However, on the upload Github says 'hidden file' and when tried to download the ZIP repo, the file isnt not there, unless its actually hidden.
Can please check and verify the file?
Thanks

**Comment by TetraTheta** [comment]
I opened new PR that _handles_ things, in opinionated way. Please check it very carefully. If you need something, feel free to tell me.
