### ISSUE TITLE
[Suggestion] More themes/modes and nugget

### ISSUE THREAD

**Issue by JeanPasquini** [BlueMystical/Dark-Mode-Forms#11]
Many people look for themes and modes in windows form, it get rich the application.

Other thing, when you put this solution in nugget is easir find your project.

**Comment by BlueMystical** [comment]
thanks for the suggestion, appreciated.

**Comment by MagicAndre1981** [comment]
+1 for nuget package. If you add [DotNet.ReproducibleBuilds](https://github.com/dotnet/reproducible-builds?tab=readme-ov-file#dotnetreproduciblebuilds-nuget-package) to the lib it adds sourcelink and embeds the debug files into the dll and with this you can step into the code like it was added directly to the solution.
