### ISSUE TITLE
toolBar.GripStyle

### ISSUE THREAD

**Issue by kachnitata** [BlueMystical/Dark-Mode-Forms#18]
hi @BlueMystical , I would like to ask you what was the motivation for the following lines in the code:

```
			if (control is ToolStrip toolBar)
			{
				toolBar.GripStyle = ToolStripGripStyle.Hidden;

```
this makes all the `ToolStrip`s locked in their positions, but I don't see any advantage of it. After commenting this line out, everything seems to work correctly and visually looks OK as well. I think a theming component should not affect the behavior unless really necessary.

**Comment by BlueMystical** [comment]
i... dont remember the why xD, if you test it with that line commented and all works feel free to Commit and Pull.
Thanks.
