### ISSUE TITLE
Fix up the ListView, Properties Window, Images

### ISSUE THREAD

**Issue by htmlsplash** [BlueMystical/Dark-Mode-Forms#2]
Can you include the ListView control styling? It doesn't look good and the colors are off in dark mode.
Same goes for properties window, tree view (that has images) and images being displayed.

**Comment by BlueMystical** [comment]
i only tested the listview in Large Icons mode, but yeah i will try to fix it.
Thanks for the report.

**Comment by htmlsplash** [comment]
FYI, can you also fix the background color when the control is disabled, it turns white.
