### ISSUE TITLE
small white box with DataGridView next to scrollbars

### ISSUE THREAD

**Issue by MagicAndre1981** [BlueMystical/Dark-Mode-Forms#24]
I have a small white box with DataGridView next to scrollbars:

![image](https://github.com/BlueMystical/Dark-Mode-Forms/assets/8274816/e66a3c83-1d1c-4655-9e03-1b63beeb0af7)

Can this be fixed?

**Comment by kachnitata** [comment]
@MagicAndre1981 in what type of Control does it happen?

**Comment by MagicAndre1981** [comment]
DataGridView as I already mentioned.

**Comment by kachnitata** [comment]
sorry, I did not notice.
I can reproduce it.
I am trying to figure out how to handle it.

**Comment by kachnitata** [comment]
I have almost found the solution.
perhaps some of my collagues will help me....

```
        grid.Paint += (object sender, PaintEventArgs e) =>
        {
          Brush brush = new SolidBrush(OScolors.Surface);//or even darker...
          var w = System.Windows.Forms.SystemInformation.VerticalScrollBarWidth;
          var h = System.Windows.Forms.SystemInformation.HorizontalScrollBarHeight;
          e.Graphics.FillRectangle(brush, e.ClipRectangle.X +e.ClipRectangle.Width-w-1,e.ClipRectangle.Y+e.ClipRectangle.Height-h-1, w, h);
        };

```

but I need to do it only if both scrollbars are currently visible. And I don't know how to determine it.

`          var s = (sender as DataGridView).ScrollBars;
`
would not help.

**Comment by kachnitata** [comment]
found it, will push soon

**Comment by kachnitata** [comment]
found it, will upload soon

**Comment by BlueMystical** [comment]
i had tested your code and it works, will wait for your commit.
Thanks!

**Comment by kachnitata** [comment]
> will wait for your commit.

Do I have to do anything? I am not sure whether i created the PR correctly, i probably somehow merged two into one.... Still getting used to GitHub.

**Comment by BlueMystical** [comment]
i just pulled it, everything is good, Thank you!

**Comment by BlueMystical** [comment]
Could maybe used a darker color like DarkSurface or even Background, but its just cosmetics ^_^

**Comment by kachnitata** [comment]
I thought of it, too. Perhaps yes.

**Comment by MagicAndre1981** [comment]
the white box that was really annoying is gone. Thanks. Maybe finetune it a bit later.

**Comment by MagicAndre1981** [comment]
With `Brush brush = new SolidBrush(Color.FromArgb(255,23,23,23));` it matches the background of the Scrollbar, which would be perfect.

But now I see several boxes in my horizontal and vertical scrollbar:

![image](https://github.com/BlueMystical/Dark-Mode-Forms/assets/8274816/4989623e-14c3-43d8-9742-0a43cd0d6d15)

Maybe [check if scrollbar reached end](https://stackoverflow.com/questions/26512977/how-can-i-detect-when-the-scroll-bar-reaches-the-end-of-a-data-grid-view) before displaying this box? @kachnitata

**Comment by kachnitata** [comment]
oh, that is really ugly. But so far I did not manage to reproduce it, Can you describe the steps, or attach a video?

**Comment by kachnitata** [comment]
I was able to reproduce something similar. Unfortunately I am busy these days so I am not sure when I find enough time to look for a fix :-(

**Comment by kachnitata** [comment]
I am probably wrong when using e.ClipRectangle, should get the position for painting in another way

**Comment by kachnitata** [comment]
i think using dgv.ClientRectangle instead of e.ClipRectangle (all instances of it) should be correct. would you test it for me, please?

**Comment by MagicAndre1981** [comment]
> i think using dgv.ClientRectangle instead of e.ClipRectangle (all instances of it)

that works 🥳 

![image](https://github.com/BlueMystical/Dark-Mode-Forms/assets/8274816/be596eaf-4979-45ab-b9b2-07cff709f6af)

No, boxes anymore.

**Comment by kachnitata** [comment]
created PR #27
