### ISSUE TITLE
Is Messenger dialogue always dark?

### ISSUE THREAD

**Issue by kachnitata** [BlueMystical/Dark-Mode-Forms#31]
hi, I recently replaced `MessageBox`es in my app with Messenger but then I found that they are always dark-themed, even when Windows is currently switched to the light theme.
Is there a way to make Messenger theme-aware?

**Comment by BlueMystical** [comment]
hi,
Not at all, Messenger should take the Windows Color Mode.
This is on Clear Mode:

![image](https://github.com/BlueMystical/Dark-Mode-Forms/assets/10116951/194ff552-70c4-404c-9b94-884fe008bd2e)

Show me how are you implementing it and i may help you to find the problem.

**Comment by kachnitata** [comment]
I will have to investigate. It was reported by a colleague who never used any dark theme and all looked normal except for the Messenger windows. I saw his screenshots.

**Comment by kachnitata** [comment]
ok, part of the mystery solved.

-In all the app's forms I am using
`      if(GlobalAppState.isThemeEnabled) _ = new DarkModeCS(this, false);`

where `GlobalAppState.isThemeEnabled `is a bool property that is set in user's profile
and because his profile has it set to false, all the forms look "normal" i.e. light. but I did not modify Messenger so it does not disable themes

-the user does not have the app installed locally, instead he is using it via Citrix remote desktop. So it is possible that Citrix is set to Dark theme even when the user is not aware of it... I myself have no access to that server so we will have to collaborate with him and explore.

so I guess we can close this ticket. Even if any problems remain, the title here would be misleading and I would report them separately.
