### ISSUE TITLE
Maximize, Minimize, Close buttons of an MDI child are too dark

### ISSUE THREAD

**Issue by kachnitata** [BlueMystical/Dark-Mode-Forms#33]
Hi, is there a way to control the style of Maximize, Minimize, Close buttons of an MDI child window?
Currently, they are black on a very dark background.
So far I found no solution...

![image](https://github.com/BlueMystical/Dark-Mode-Forms/assets/168674258/72805b8f-d077-445d-a265-7b76f6497cc9)

**Comment by BlueMystical** [comment]
oh! i did not tried MDI, gonna see what i can find about it

**Comment by kachnitata** [comment]
What I found so far: the background color is taken from the MDI parent window's `MenuStrip`'s `BackColor` but the foreground seems to be always black. So when I force it to have yellow background and green foreground, it looks like this:
![image](https://github.com/BlueMystical/Dark-Mode-Forms/assets/168674258/5e1b62d3-49ba-4103-a3c2-eea9bf3642cb)

**Comment by kachnitata** [comment]
by the way, I noticed a little confusing piece of code:

```
      if (control is MenuStrip menu)
      {
        menu.RenderMode = ToolStripRenderMode.Professional;
        menu.Renderer = new MyRenderer(new CustomColorTable(OScolors), ColorizeIcons)
        {
          MyColors = OScolors
        };
      }
      if (control is ToolStrip toolBar)
      {
        //commented out because it would just freeze the toolstrips with no obvious benefit:
        //toolBar.GripStyle = ToolStripGripStyle.Hidden;
        toolBar.RenderMode = ToolStripRenderMode.Professional;
        toolBar.Renderer = new MyRenderer(new CustomColorTable(OScolors), ColorizeIcons) { MyColors = OScolors };
      }

```

here, if we have a `MenuStrip`, both blocks are executed because MenuStrip inherits from `ToolStrip`. It makes no harm as the two blocks of code are currently identical but might be confusing in the future...

**Comment by kachnitata** [comment]
I am almost there. I found that those three "window controls" are represented by `System.Windows.Forms.MdiControlStrip.ControlBoxMenuItem` instances and added to the `DisplayedItems` collection of the `MenuStrip`  and are handled in OnPaint() method of `ToolStrip` (which is parent class for `MenuStrip`)

![image](https://github.com/BlueMystical/Dark-Mode-Forms/assets/168674258/5a039505-770d-405b-8325-4e221588fdd8)

**Comment by kachnitata** [comment]
and themseves painted in `ToolStripMenuItem.OnPaint()`. Enough for today...

**Comment by BlueMystical** [comment]
Perfect! thanks you for all your work.

**Comment by kachnitata** [comment]
I tracked it all the way back to `DarkModeCS.OnRenderItemImage()` :-) 

there I handle the case

`        if (e.Item.GetType().FullName == "System.Windows.Forms.MdiControlStrip+ControlBoxMenuItem")
`

in a similar way you did `ColorizeIcons`, and then I am able to adjust the color.

I will post a PR when I complete it.

**Comment by kachnitata** [comment]
I created a PR #34 for this feature.
Because there is my PR #32  still pending, I created a separate branch for PR #34, I hope I did it correctly.
