### ISSUE TITLE
Project isn't compatible with .NET Framework that uses C# 7.3

### ISSUE THREAD

**Issue by TetraTheta** [BlueMystical/Dark-Mode-Forms#4]
In [`Messenger.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/48e6c57b186227a04f7da6b123e592a4c6c6d04c/Messenger.cs), this line has a problem.

https://github.com/BlueMystical/Dark-Mode-Forms/blob/48e6c57b186227a04f7da6b123e592a4c6c6d04c/Messenger.cs#L21

Visual Studio reports that nullable reference types is available above C# 8.0 which is higher version that .NET Framework uses(C# 7.3).

Thus, that line should be changed to be like this:
```csharp
private static Action<object, ValidateEventArgs> ValidateControlsHandler; 
```

Here are other lines that uses nullable reference types.

https://github.com/BlueMystical/Dark-Mode-Forms/blob/48e6c57b186227a04f7da6b123e592a4c6c6d04c/DarkModeCS.cs#L393

https://github.com/BlueMystical/Dark-Mode-Forms/blob/48e6c57b186227a04f7da6b123e592a4c6c6d04c/DarkModeCS.cs#L562

---

This suggestion is irrelevant to this issue.

Since [`Messenger.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/48e6c57b186227a04f7da6b123e592a4c6c6d04c/Messenger.cs) depends on [`FlatComboBox.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/48e6c57b186227a04f7da6b123e592a4c6c6d04c/Example/DarkModeForms/FlatComboBox.cs), shouldn't `FlatComboBox.cs` be put at the same level of `Messenger.cs`?

https://github.com/BlueMystical/Dark-Mode-Forms/blob/48e6c57b186227a04f7da6b123e592a4c6c6d04c/Messenger.cs#L715

[`DarkModeCS.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/48e6c57b186227a04f7da6b123e592a4c6c6d04c/DarkModeCS.cs) also depends on [`FlatTabControl.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/48e6c57b186227a04f7da6b123e592a4c6c6d04c/Example/DarkModeForms/FlatTabControl.cs), but since it is inside of `if` statement, I think it is fine.

https://github.com/BlueMystical/Dark-Mode-Forms/blob/48e6c57b186227a04f7da6b123e592a4c6c6d04c/DarkModeCS.cs#L373

**Comment by BlueMystical** [comment]
i'm gonna need to test this out.
