### ISSUE TITLE
[NotifyIcon] Can NotifyIcon's ContextMenu support dark mode?

### ISSUE THREAD

**Issue by emako** [BlueMystical/Dark-Mode-Forms#41]

**Comment by BlueMystical** [comment]
Yes it can,  thanks for the suggestion, i'll implement it on the next update.
May take a little because of RL complications, but i'll be on it.
Regards.

**Comment by BlueMystical** [comment]
hi again, sorry for the late, i had a lot of RL work,
however the requested feature for NotifyIcon and its context menus its been added on v1.8.3
Check the Example Project
![Sin título](https://github.com/user-attachments/assets/8b6b2df5-3740-4600-9262-d3d50f5a1fa2)
