### ISSUE TITLE
Using Button Image

### ISSUE THREAD

**Issue by BLahne** [BlueMystical/Dark-Mode-Forms#42]
button.Image is not displayed after using DarkModeCS

![ButtonImage](https://github.com/user-attachments/assets/91af49a3-12eb-438b-a40c-a95088dddde6)

**Comment by Aniobodo** [comment]
I had a similar (**but not the same**) with button. Setting a BackColor in Dark Mode did not reflect. But I found a way out of it by resetting the FlatStyle of the button to Flat.

**Comment by BlueMystical** [comment]
Ohh i did not tested buttons with images, 
Thanks for reporting this,
Will be fixed on the next patch.

**Comment by BLahne** [comment]
Thanks, it works :-)

**Comment by Bartq95** [comment]
Hello, I have the same problem. After enabling dark mode all pictures from buttons are gone.
![Tabelarka_dark](https://github.com/user-attachments/assets/5f611bb5-03f9-47b8-9f5a-1da08390bfec)

**Comment by BLahne** [comment]
Hallo Bartq95,
have you seen the comment from Aniobodo above (FlatStyle to Flat).
button.FlatStyle = IsDarkMode ? FlatStyle.Flat : FlatStyle.Standard;
![image](https://github.com/user-attachments/assets/a44611b6-e6f4-4246-8046-87688314f74a)

**Comment by Bartq95** [comment]
> Hallo Bartq95, have you seen the comment from Aniobodo above (FlatStyle to Flat). button.FlatStyle = IsDarkMode ? FlatStyle.Flat : FlatStyle.Standard; ![image](https://private-user-images.githubusercontent.com/68509233/378341254-a44611b6-e6f4-4246-8046-87688314f74a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDA5MzUsIm5iZiI6MTcyOTUwMDYzNSwicGF0aCI6Ii82ODUwOTIzMy8zNzgzNDEyNTQtYTQ0NjExYjYtZTZmNC00MjQ2LTgwNDYtODc2ODgzMTRmNzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDA4NTAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMDExNmIzZDE3OWVkYTFlZjAyYTBjYWU1ZTVmY2FmOTZiNTdlMzhjZjRlOTdjZmI0OTRjZWFlYTVmYjQxZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LJ_BU4KgHKJE3LLD--qJKrp59bVAR7lfAztuiaH1Qhc)

Hello BLahne,

in my app i dynamically add new buttons. I've addes flat style but image does not show at all.
I'm a newbie programmer, maybe something i did wrong. Please take a look.
Addnig new button is done after set dark mode.

![image](https://github.com/user-attachments/assets/d3a3fd22-0faa-42cb-a52d-493644d8beb7)

**Comment by BLahne** [comment]
This is my test:
![image](https://github.com/user-attachments/assets/74346bf7-fd4d-4731-9480-a405ed16bafa)

in class DarkModeCS at Line 368:
![image](https://github.com/user-attachments/assets/68e11878-629c-409a-a1f5-21a0575f8bb4)

My result:
![image](https://github.com/user-attachments/assets/b374914f-09ee-4890-90f6-11d001290293)

**Comment by Bartq95** [comment]
It's working :) Thank you very much. 

![image](https://github.com/user-attachments/assets/909cd952-cf57-4487-9d8e-22346786e9d9)

**Comment by BlueMystical** [comment]
hi folks,
Many thanks for your bug reports and contributions.

@BLahne i had modified the Code to add your fix:

![image](https://github.com/user-attachments/assets/97017c0a-f396-4997-a9b6-bd1717f40890)
