### ISSUE TITLE
CheckBox Enabled = False

### ISSUE THREAD

**Issue by BLahne** [BlueMystical/Dark-Mode-Forms#44]
![image](https://github.com/user-attachments/assets/cab0a8df-c71d-4fa2-90c9-f31395167366)
The ForeColor is not useful in DarkMode.
Is there a quick fix?

Thanks for any help

**Comment by BlueMystical** [comment]
hi, thanks for reporting this glitch, ill make sure to fix it on the next patch
as for a quick workaround you can change the ForeColor property of the control to a Color near to White
if the color is white the algorythm will try to re-color it, which is what causes this isssue, but if its not white it should leave it as it is.
Please try and tell me if it works.

**Comment by BLahne** [comment]
![image](https://github.com/user-attachments/assets/e3a508ca-7d14-4b36-90e0-fb67c02f8ca7)
![image](https://github.com/user-attachments/assets/d4af8b62-11db-4802-8e1d-2b4e6d37eda1)
hi, thanks for your answer.
I changed the ForeColor to Yellow, but it doesn't work:
		private void button7_Click(object sender, EventArgs e)
		{
			if (testCheckBox.Enabled)
			{
				testCheckBox.Enabled = false;
				if (IsDarkMode) 
				{
					testCheckBox.ForeColor = Color.Yellow; 
				}
				button7.Text = "enable Checkbox";
			}
			else
			{
				testCheckBox.Enabled = true;
				if (IsDarkMode) 
				{
					testCheckBox.ForeColor = Color.White; 
				}
				button7.Text = "disable Checkbox";
			}
		}
My solution:
![image](https://github.com/user-attachments/assets/8a746d54-7a13-45c6-8d18-a69f6a2caded)
A control with label and picturebox

**Comment by BlueMystical** [comment]
Alright,
This glitch is now fixed:
![image](https://github.com/user-attachments/assets/021aca88-74cd-4fcd-9e90-ff11ccc1cfca)
Although it may look a little weird when on clear Mode
Further polishing may be necessary.

Will be up in the next patch, today hopefully.
