### ISSUE TITLE
`FlatTabControl` not works under light (default) mode?

### ISSUE THREAD

**Issue by lzcapp** [BlueMystical/Dark-Mode-Forms#46]
![Snipaste_2024-09-12_14-40-16](https://github.com/user-attachments/assets/1f18be8b-c1e7-4927-b2c7-56573070595a)

![Snipaste_2024-09-12_15-00-32](https://github.com/user-attachments/assets/07b8cd49-ea19-4341-a541-2f2d98ec3498)

`FlatTabControl` not works under light (default) mode?

**Comment by lzcapp** [comment]
@BlueMystical I have a treeview control that docked inside the tabpage, it works well with the normal TabControl, but with FlatTabControl, the contorl seems to be unable to dock anymore (shrinked).
PS: I works with the winform designer, and because I originally uses the TabControl, I simply changes the TabControl to FlatTabControl in the designer source code.

![image](https://github.com/user-attachments/assets/ea843e18-7dc3-453f-930d-5b016087b742)
![image](https://github.com/user-attachments/assets/b55bb98a-1c74-48f5-838d-efa90cdf6b04)

Thank you for looking into this issue and wish you a nice day! ❤️

**Comment by lzcapp** [comment]
Seems fine now, oddly enough. (I think VS's desinger is to be blamed. I have seen many wierd things with it.)
@BlueMystical Thanks again!

![image](https://github.com/user-attachments/assets/bf6da472-4099-41bf-bd28-1ac977ae700e)

**Comment by BlueMystical** [comment]
Great!, thanks for letting me know.
