### ISSUE TITLE
Accelerator key label text is wrong if target control is disabled

### ISSUE THREAD

**Issue by TheIronWolfModding** [BlueMystical/Dark-Mode-Forms#50]
Hi,
It's me again :D  Small bug (Note "&Focus ID" label):

![image](https://github.com/user-attachments/assets/b4488d09-1adf-4d6c-85c6-b4457bdefe5d)

Once target control is enabled, all is good:

![image](https://github.com/user-attachments/assets/26553447-224e-4192-af41-535b11ed7cfb)

**Comment by BlueMystical** [comment]
you mean the & symbol on it? thats very weird..

**Comment by BlueMystical** [comment]
and it shows the & when it gets the focus only?

**Comment by kachnitata** [comment]
hi, I came across this conversation.
I think the reason is obvious in the code below:

```
			if (control is Label)
			{
				control.GetType().GetProperty("BackColor")?.SetValue(control, control.Parent.BackColor);
				control.GetType().GetProperty("BorderStyle")?.SetValue(control, BorderStyle.None);
				control.Paint += (object sender, PaintEventArgs e) =>
				{
					if (control.Enabled == false && this.IsDarkMode)
					{
						var radio = (sender as Label);
						Brush B = new SolidBrush(control.ForeColor);

						e.Graphics.**DrawString(radio.Text**, radio.Font,
						  B, new System.Drawing.PointF(1, 0));
					}
				};
			}

```

**Comment by kachnitata** [comment]
I looked into the refactored code of `Label.OnPaint()` and found this:

`              e.Graphics.DrawString(this.Text, this.Font, brush, (RectangleF) rectangle, stringFormat);
`

and


`    internal virtual StringFormat CreateStringFormat() => ControlPaint.CreateStringFormat((Control) this, this.TextAlign, this.AutoEllipsis, this.UseMnemonic);
`

The key thing is the `UseMnemonic`:

Gets or sets a value indicating whether the control interprets an ampersand character (&) in the control's [Text] property to be an access key prefix character.

[](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.label.usemnemonic?view=windowsdesktop-8.0)

**Comment by kachnitata** [comment]
actually, depending on the settings they use also `TextRenderer.DrawText` instead of `Graphics.DrawString` etc.
I have no idea what details we will have to go into within DarkModeCS.

The whole method looks like this:

```
    protected override void OnPaint(PaintEventArgs e)
    {
      this.Animate();
      ImageAnimator.UpdateFrames(this.Image);
      Rectangle rectangle = LayoutUtils.DeflateRect(this.ClientRectangle, this.Padding);
      Image image = this.Image;
      if (image != null)
        this.DrawImage(e.Graphics, image, rectangle, this.RtlTranslateAlignment(this.ImageAlign));
      IntPtr hdc = e.Graphics.GetHdc();
      Color nearestColor;
      try
      {
        using (WindowsGraphics windowsGraphics = WindowsGraphics.FromHdc(hdc))
          nearestColor = windowsGraphics.GetNearestColor(this.Enabled ? this.ForeColor : this.DisabledColor);
      }
      finally
      {
        e.Graphics.ReleaseHdc();
      }
      if (this.AutoEllipsis)
      {
        Rectangle clientRectangle = this.ClientRectangle;
        Size preferredSize = this.GetPreferredSize(new Size(clientRectangle.Width, clientRectangle.Height));
        this.showToolTip = clientRectangle.Width < preferredSize.Width || clientRectangle.Height < preferredSize.Height;
      }
      else
        this.showToolTip = false;
      if (this.UseCompatibleTextRendering)
      {
        using (StringFormat stringFormat = this.CreateStringFormat())
        {
          if (this.Enabled)
          {
            using (Brush brush = (Brush) new SolidBrush(nearestColor))
              e.Graphics.DrawString(this.Text, this.Font, brush, (RectangleF) rectangle, stringFormat);
          }
          else
            ControlPaint.DrawStringDisabled(e.Graphics, this.Text, this.Font, nearestColor, (RectangleF) rectangle, stringFormat);
        }
      }
      else
      {
        TextFormatFlags textFormatFlags = this.CreateTextFormatFlags();
        if (this.Enabled)
        {
          TextRenderer.DrawText((IDeviceContext) e.Graphics, this.Text, this.Font, rectangle, nearestColor, textFormatFlags);
        }
        else
        {
          Color foreColor = TextRenderer.DisabledTextColor(this.BackColor);
          TextRenderer.DrawText((IDeviceContext) e.Graphics, this.Text, this.Font, rectangle, foreColor, textFormatFlags);
        }
      }
      base.OnPaint(e);
    }

```

**Comment by BlueMystical** [comment]
Ufff that look deep!
Thanks for taking the time to investigate this.

**Comment by BlueMystical** [comment]
i think i fixed this issue:

![image](https://github.com/user-attachments/assets/afb8a91c-96dd-42c9-904a-0ba1cd17ffa0)

The assigned 'Mnemonic' will show up as soon as you hit the ALT key, and will stay afterwards !
Going to Commit in a few mins and if @kachnitata and you (@TheIronWolfModding ) can test it and report back it would be great.
Thanks folks!

**Comment by kachnitata** [comment]
I am having the same issue. I think you @BlueMystical made two mistakes:

`using (Graphics g = e.Graphics)` would cause `Disopose()` of `e.Graphics` which probably leads to the errror

what I meant in my former post was to add style to the `DrawString` Call (instead of setting `UseMnemonic`)

I am going to fix it and post my solution

**Comment by kachnitata** [comment]
also I am not sure if we can


```
						e.Graphics.Clear(control.Parent.BackColor);
						e.Graphics.SmoothingMode = SmoothingMode.HighQuality;

```

maybe we should create new Grephics instance for it....

**Comment by BlueMystical** [comment]
@TheIronWolfModding : yes, a little bit:
- Give your Form Inheritance:  `public partial class Form1 : **DarkModeBaseForm**`
and then:
```csharp
                public Form1()
		{
			InitializeComponent();
			base.dm = new DarkModeCS(this);
		}
```

**Comment by kachnitata** [comment]
Hi, I haven't noticed any issues myself.

btw @BlueMystical I think we really have to deal with the line
`e.Graphics.SmoothingMode = SmoothingMode.HighQuality;`
either get rid of it, or create a new instance somehow like: `using g=new Graphics()`  (I haven't tried it yet and I am out of office right now)

as the `e.Graphics` might be shared by multiple controls, it would unpredictably affect their smoothing mode. who knows, perhaps this leads to the issues reported by @TheIronWolfModding (but I was not able to reproduce in my app). I think that was your original point with the using block, you just put there e.Graphics by mistake...

**Comment by BlueMystical** [comment]
yeah that can be done, i used the SmoothingMode  because i tough it would look a bit better, but it doesnt make much difference.
