### ISSUE TITLE
How to ignore dark mode for selected controls?

### ISSUE THREAD

**Issue by panyann** [BlueMystical/Dark-Mode-Forms#52]
Hello,
I tried the theme and it's looking very nice, but I already have some customized controls (like a red button) and the theme is replacing it with the dark mode...
Is there any way to ignore the dark mode for selected controls?

I also have extra question, where in the DarkModeCS you apply a dark color for a TextBox BackColor? What color is it?

Thanks.

**Comment by kachnitata** [comment]
hi @BlueMystical I just realized I would need it myself, too. So I am gonna create a PR for it

**Comment by BlueMystical** [comment]
Great!, thank you.
