### ISSUE TITLE
Messenger.MessageBox doesn't scale with system scaling

### ISSUE THREAD

**Issue by panyann** [BlueMystical/Dark-Mode-Forms#54]
Hi,
Seems like the `Messenger.MessageBox` doesn't scale with system settings:
![image](https://github.com/user-attachments/assets/bf80adc4-be0f-4515-8a3a-a23c5fa9a1a7)

I have 200% scale set.

**Comment by BlueMystical** [comment]
hi, thanks for the report, i'll get into it.
Regrads.

**Comment by panyann** [comment]
Thank you for your work 🙂

**Comment by BlueMystical** [comment]
ok,
This issue will be fixed on the next Release v1.8.11, hopefully today late.
![image](https://github.com/user-attachments/assets/210c6982-c7b2-4c2e-bccf-89fe3dab0065)
