### ISSUE TITLE
ListView Scrollbar is not themed

### ISSUE THREAD

**Issue by tGecko** [BlueMystical/Dark-Mode-Forms#57]
Scrollbar of ListViews don't appear to be themed
![image](https://github.com/user-attachments/assets/1397688b-88ef-4013-9351-8552b55941de)

ListBox for comparison:
![image](https://github.com/user-attachments/assets/25b99ea2-9807-4513-8f27-9e36a1bc4739)

**Comment by BlueMystical** [comment]
List View in Details mode?

**Comment by tGecko** [comment]
Yes, details mode.

**Comment by BlueMystical** [comment]
ok, this is now fixed, 
will be on the next patch, today hopefully
Regards,
![image](https://github.com/user-attachments/assets/7b4cf2e3-3e4e-41b0-a47b-ae42f6620756)
