### ISSUE TITLE
No DarkModePolicy in DarkModeForms?

### ISSUE THREAD

**Issue by lzcapp** [BlueMystical/Dark-Mode-Forms#69]
No `DarkModePolicy` in `DarkModeForms`?

![image](https://github.com/user-attachments/assets/ee06fe83-2c26-4e3b-87d5-6747c3b09f0e)

**Comment by kachnitata** [comment]
When they introduced `DarkModePolicy` they put it in a new, separate source file.

**Comment by BlueMystical** [comment]
im gonna rework all that, probably into a Enum Property used by the constructor with a default value to 'System Mode' the other values will be 'Clear Mode and Dark Mode' this way it will have minimal or no effect in existing implementations and the whole thing will be again "Easy to use"

i may also get rid of the "IsDarkMode" variable, it leads to too may confusions...

Apologies for the 'dirty' current code, i was implementing the Darkmode Class (alone) into a brand new project and i simply commented everything that refused to work.

**Comment by kachnitata** [comment]
I think the enum is a great idea , it could also absorb the `IsDarkModeCsEnabled` functionality which I introduced a little earlier, by adding a new enum value....

**Comment by BlueMystical** [comment]
ok, v1.8.13 is up, i believe it solves everything.
Let me know what you guys think.
